### ISSUE TITLE
Is this compatible with postgresql for production enviornment

### ISSUE THREAD

**Issue by samtheloanman** [app-generator/django-dashboard-atlantis-dark-pro#1]
I was wondering if this is compatible with postgresql implementation of django.  I read on the product page that it is compatible with SQlite and ORM but did not see postgresql mentioned.

**Comment by app-generator** [comment]
Hello @samtheloanman, 

To switch from SQLite to PostgreSQL a single section should be updated in the settings file.

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'postgre': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': ‘<db_name>’,
        'USER': '<db_username>',
        'PASSWORD': '<password>',
        'HOST': '<db_hostname_or_ip>',
        'PORT': '<db_port>',
    }
}
``` 

Also, `requirements.txt` must include `psycopg2` dependency and a usable PostgreSQL server should be available.

For more information and updates, feel free to join [AppSeed](https://appseed.us/) newsletter or the [Discord](https://discord.gg/fZC6hup) community. 

I will close this issue.
